### PR TITLE
Wrap long lines

### PR DESCRIPTION
**Pull request by bdrung**
The Markdown files and pylint.rc include line lengths that are well beyond the line length for reading without the need for horizontal scrolling.

Wrap lines in Markdown files after 120 characters and wrap list of checks to disable for pylint. Keep the Markdown tables untouched.

### CODE REVIEW

**Comment by bdrung** [comment]
The syntax for pylint works (I am using that format in other projects like apport). Should I put that change in a separate merge request?

I still prefer to wrap the lines in the Markdown files regardless of editing them mostly with a proper Markdown editor. Then they can be nicely read with simple tools like simple text editors or vim/less on the command line.

**Comment by martin-belanger** [comment]
> The syntax for pylint works (I am using that format in other projects like apport). Should I put that change in a separate merge request?

Yes, please submit a separate PR just for the pylint file.

> 
> I still prefer to wrap the lines in the Markdown files regardless of editing them mostly with a proper Markdown editor. Then they can be nicely read with simple tools like simple text editors or vim/less on the command line.

I'm the main editor/maintainer for the MD files. I prefer using the right tool (typora) for the job. I do not want to have to manually have to manage the line lengths. In other words, I do not want to change the MD files.

**Comment by bdrung** [comment]
Since you rejected the change for the Markdown files, I updated this merge request to only include the pylint.rc change.

**Comment by martin-belanger** [comment]
Thanks!

**Pull request merged**
